@echo off
chcp 65001 > nul

cd /d "%~dp0"

:: 1. Get the folder path
set "TARGET_DIR=%~1"

if "%TARGET_DIR%"=="" (
    echo ============================================================
    echo  Please enter or paste the target folder path.
    echo ============================================================
    set /p "TARGET_DIR= Folder Path > "
)

set "TARGET_DIR=%TARGET_DIR:"=%"
:: Remove trailing backslash if it exists
if "%TARGET_DIR:~-1%"=="\" set "TARGET_DIR=%TARGET_DIR:~0,-1%"

if "%TARGET_DIR%"=="" (
    echo.
    echo [Canceled] No folder path specified.
    goto END
)

:: 2. Install all required libraries at once
echo.
echo ============================================================
echo  Checking and installing all required libraries...
echo ============================================================
python -m pip install moviepy openai-whisper boto3 tqdm

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Failed to install libraries. Please check the error message above.
    goto END
)

:: 3. Run the first script (clean_json.py)
echo.
echo ============================================================
echo  [Step 1] Processing files (clean_json.py)
echo ============================================================
echo Target: %TARGET_DIR%
echo.
python clean_json.py "%TARGET_DIR%"

:: Get the subfolder name generated by clean_json.py (TARGET_DIR\FOLDER_NAME)
for %%I in ("%TARGET_DIR%") do set "SUB_FOLDER=%%~nxI"
set "UPLOAD_DIR=%TARGET_DIR%\%SUB_FOLDER%"

:: 4. Run the second script (upload_aws.py) using the generated subfolder
echo.
echo ============================================================
echo  [Step 2] Uploading files (upload_aws.py)
echo ============================================================
echo Target: %UPLOAD_DIR%
echo.
python upload_aws.py "%UPLOAD_DIR%"

:END
echo.
echo ==========================================
echo  All processes finished.
echo ==========================================